name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:
  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86, x64]
        configuration: ['Debug', 'Release']

    steps:

      - name: Start Windows Audio engine
        run: net start audiosrv

      - name: Install Sound Device
        uses: LABSN/sound-ci-helpers@v1.0.3
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install x264 VFW Codec
        run: |
          3rdParty\x264vfw_${{ matrix.platform }}_v200_x264b159_10bit_20200321.exe /S
          sleep 1
        
      #- if: matrix.configuration == 'Release'
      #  name: Install Microsoft Visual Studio Installer Projects Extension
      #  uses: microcompiler/install-vsix@main
      #  with: 
      #    packagename: 'VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects'
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: VisualC/vcpkg.json
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'

      - name: Restore vcpkg packages
        working-directory: VisualC
        run: vcpkg integrate install --vcpkg-root '${{ runner.workspace }}\\b\\vcpkg'
        
      - name: Run MSBuild
        run: msbuild VisualC/Scion.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}  

      - name: Run Tests
        uses: rusty-bender/vstest-action@main
        with:
          testAssembly: |
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Audio.Test.dll     
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Graphics.Test.dll     
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Video.Test.dll     
