name: MSBuild

on:

  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:

  build:
  
    name: ${{ matrix.os }} ${{ matrix.platform }} ${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86, x64]
        configuration: ['Debug', 'Release']

    steps:

      - name: Start Windows Audio engine
        run: net start audiosrv

      - name: Install Sound Device
        uses: LABSN/sound-ci-helpers@v1.0.3
        
      - name: Checkout code
        uses: actions/checkout@v3
            
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Install Microsoft Visual Studio Installer Projects Extension
        shell: pwsh
        run: |
          $vsixPackage= "VisualStudioClient.MicrosoftVisualStudio2022InstallerProjects"
          $vsixPackageUrl = Get-VsixExtenstionFromMarketplace -ExtensionMarketPlaceName $vsixPackage
          $FilePath = Start-DownloadWithRetry -Url $vsixPackageUrl.DownloadUri -Name $vsixPackage.FileName
          $argumentList = ('/quiet', "`"$FilePath`"")
          Start-Process -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VSIXInstaller.exe" -ArgumentList $argumentList -Wait -PassThru
    
      - name: Run MSBuild
        run: msbuild VisualC/Scion.sln -property:Configuration=${{ matrix.configuration }} -property:Platform=${{ matrix.platform }}  

      - name: Run Tests
        uses: rusty-bender/vstest-action@main
        with:
          testAssembly: |
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Audio.Test.dll     
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Graphics.Test.dll     
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/Scion-Video.Test.dll     

      - uses: actions/upload-artifact@v3
        with:
          name: binaries-artifact
          path: |
            include  
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/*.lib
            VisualC/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb
